### ISSUE TITLE
Licensebat reports unauthorized licenses for some packages when package-lock version is 3

### ISSUE THREAD

**Issue by tsimbalar** [licensebat/licensebat#45]
After upgrading to Node v18 (v18.15.0) and implicitly npm 9 (9.5.0), deleting the package-lock and recreating it, Licensebat reports invalid licenses for some packages

![image](https://github.com/licensebat/licensebat/assets/160544/26063b33-a93a-48d7-a368-82531d9e2ca4)

Note that it now shows 51 invalid dependencies. 

Prior to the change it was all green : 
![image](https://github.com/licensebat/licensebat/assets/160544/87bdfc14-ebf1-460d-b4a3-14efb2b8e39a)

Interestingly, in the list of invalid packages, the links point to packages that don't exist (note the "deep name" with several slashes , and links pointing to nowhere)

I'm expecting there might be some sort of parsing issue somewhere 🤔 

## More info 

here's our GitHub Action workflow : 

```yaml
name: Licensebat

on:
  push:
    branches:
      - master
  # all PRs should trigger, no matter the branch
  pull_request:

jobs:
  licenses:
    runs-on: ubuntu-20.04
    name: License Compliance
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name:Licensebat
        uses: licensebat/licensebat-action@b931b12f3b428c40adbb00825820b485c765ee04 # pin@v5
        with:
          dependency-file-path: "package-lock.json"
```

Here is our `.licrc` file

```
[licenses]
# This indicates which are the only licenses that Licensebat will accept.
# The rest will be flagged as not allowed.
# Source of Truth at COMPANYNAME is : CONFLUENCE_LINK
# the docs for this config file: https://github.com/licensebat/licensebat/blob/master/licensebat-cli/README.md#the-licrc-file
accepted = [
  "MIT",
  "MSC",
  "BSD",
  "BSD-2-Clause",
  "BSD-3-Clause",
  "Apache-2.0",
  "Apache 2.0",
  "ISC",
  "AFLv2.1",
  "BSD-like",
  "EPL-1.0",
  "0BSD",
  "(MIT AND Zlib)",
  "(MIT OR CC0-1.0)",
  "(MIT AND Apache-2.0)",
  "(MIT OR Apache-2.0)",
  "(MIT AND BSD-3-Clause)",
  "BSD-3-Clause OR MIT",
  "CC-BY-3.0",
  "CC-BY-4.0",
  "CC0-1.0",
  "Unlicense",
  "Public Domain",
  "Python-2.0"
  ]
# This will indicate which licenses are not accepted.
# The rest will be accepted, except for the unknown licenses or dependencies without licenses.
# unaccepted = ["LGPL"]
# Note that only one of the previous options can be enabled at once. 
# If both of them are informed, only accepted will be considered.

[dependencies]
# This will allow users to flag some dependencies so that Licensebat will not check for their license.
# ignored=[]
# False by default, if true it will mark all dev dependencies as ignored.
ignore_dev_dependencies = true

[behavior]
# False by default, if true, it will only run the checks when one of the dependency files or the .licrc file has been modified.
run_only_on_dependency_modification = true
# False by default, if true, it will never block the build.
do_not_block_pr = false
# False by default, if true it will do not show the dev dependencies in the final report.
do_not_show_dev_dependencies = true
```

**Comment by tsimbalar** [comment]
OK, nevermind, after upgrading to lated version of `licensebat-action` , everything works out just fine :) 🚀 

```yaml
      - name: Licensebat
        uses: licensebat/licensebat-action@cc63ce2da98e1e00ffcd7c0d5485c9e783abb2df # pin@v6
        with:
          dependency-file-path: "package-lock.json"
```

Hopefully this issue will be useful for future archeologists :)
